Repository SMU-IS/IS212-T7, pull requests merged in 2024-10, with the labels that each got.

#101 feat: add new notification method for approval
  backend/src/config/mailer.ts
  backend/src/services/NotificationService.test.ts
  backend/src/services/NotificationService.ts
  backend/src/services/ReassignmentService.ts
Labels: ready for review

#102 test: improve test coverage
  backend/src/config/mailer.test.ts
  backend/src/database/LogDb.test.ts
  backend/src/database/ReassignmentDb.test.ts
  backend/src/database/RequestDb.test.ts
  backend/src/database/WithdrawalDb.test.ts
Labels: ready for review

#109 feat: huat ah integration test working lo
  backend/package.json
  backend/src/controllers/EmployeeController.integration.test.ts
Labels: enhancement

#119 fix: reassignment to same level, request logs privilege for role 3
  backend/src/config/index.ts
  backend/src/controllers/ReassignmentController.ts
  backend/src/controllers/RequestController.test.ts
  backend/src/database/EmployeeDb.ts
  backend/src/database/LogDb.ts
  backend/src/helpers/index.ts
  backend/src/router/index.ts
  backend/src/services/EmployeeService.test.ts
  backend/src/services/EmployeeService.ts
  backend/src/services/LogService.test.ts
  backend/src/services/LogService.ts
  backend/src/services/ReassignmentService.ts
  backend/src/services/RequestService.test.ts
  backend/src/services/RequestService.ts
  backend/src/services/WithdrawalService.test.ts
  backend/src/services/WithdrawalService.ts
Labels: ready for review

#122 test: add integration test for reassignment API
  backend/script/reassignment.json
  backend/src/controllers/ReassignmentController.integration.test.ts
  backend/src/database/ReassignmentDb.ts
  backend/src/services/ReassignmentService.test.ts
Labels: documentation

#126 test: add integration test for logs controller
  backend/src/controllers/LogController.integration.test.ts
Labels: documentation

#125 test: add integration test for request controller
  backend/script/request.json
  backend/src/config/mailer.ts
  backend/src/controllers/LogController.test.ts
  backend/src/controllers/RequestController.integration.test.ts
Labels: documentation
